dbt_privacy_integration_tests:
  target: pg
  outputs:
    pg:
      type: postgres
      host: localhost
      user: test_user
      password: for_testing_only
      port: 5432
      dbname: postgres
      schema: dbt_privacy
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default
      connect_timeout: 10 # default 10 seconds
